### ISSUE TITLE
Full In-Browser CoinJoin Demo

### ISSUE THREAD

**Issue by jojobyte** [dashhive/ledger#1]
Re: https://github.com/dashhive/DashJoin.js/pull/31, https://github.com/dashhive/DashRPC.js/pull/14, and https://github.com/dashhive/DashSight-Server.js/pull/4

- [x] Fully convert to WebSockets
- [x] Fully convert to Uint8Array / ArrayBuffer 
- [x] Full browser demo w/ DashSight-Server as proxy

**Comment by coolaj86** [comment]
@jojobyte Claiming 0 DASH for this as it has been assimilated into other project tasks.

**Comment by coolaj86** [comment]
@jojobyte Claiming

Address: XjW4QR88HW5NUCo4JLLr4smqyFtZWLLKP2

Deliverables:
- See linked PRs

This shows that there is both a CLI client and a Web client as participants in a CoinJoin session that ends successfully (the errors were due to a typo in post-success cleanup).

![Image](https://github.com/user-attachments/assets/81930641-d0e9-4716-97f7-3686fedfded2)

**Comment by jojobyte** [comment]
Approved @coolaj86
