### ISSUE TITLE
Librarify DashJoin publish working Demo

### ISSUE THREAD

**Issue by jojobyte** [dashhive/ledger#3]
Turn the CLI / WebSocket demo into a reusable library suitable for The Web, and create a deployable site that works with testnet.

**Comment by coolaj86** [comment]
@jojobyte Claiming this task for 100 DASH.

Address: Xj6BQm57L1qkihDEda6QQErDZFYDyG2FLF

Commits since Aug 13+ at: https://github.com/dashhive/DashJoin.js/pull/29/commits

Deploying demo to <https://dashhive.github.io/DashJoin.js/> momentarily. When we're a little further along I'll also deploy the mainnet version.

**Comment by jojobyte** [comment]
@coolaj86 Approved.

**Comment by coolaj86** [comment]
Demo is up at https://dashhive.github.io/DashJoin.js/

Since I've already verified the other domain with the DigitalCashDev org I'll wait until the next iteration to deploy it to https://coinjoin.digitalcash.dev and list on https://digitalcash.dev.
